### ISSUE TITLE
Personal Vercel Deployment Error

### ISSUE THREAD

**Issue by TurnipGuy30** [FlyN-Nick/hacked-github-stat-trophies#2]
Hi @FlyN-Nick, I haven't used Vercel before, and created a deployment for [my fork of your repo](https://github.com/TurnipGuy30/hacked-github-stat-trophies). Can you please help me get it working? The deployment is [here](https://hacked-github-stat-trophies-three.vercel.app/), and I've changed the following in `src/card.ts` according to your README:
```
// LINE #50
let wantAllSuperRank = true;
let wantLongTimeAccount = true;
let wantAncientAccount = true;
let wantJoined2020 = true;
```
Thank you in advance!

**Comment by FlyN-Nick** [comment]
Hi @TurnipGuy30, looking at the code you changed, what is probably occurring is that adding one or more of these trophies is resulting in some sort of error in the code. I suggest first returning the code in `src/card.ts` back to
```
// LINE #50
let wantAllSuperRank = true;
let wantLongTimeAccount = false;
let wantAncientAccount = false;
let wantJoined2020 = false;
```
just to make sure that it isn't an issue with your vercel deployment itself. I find it unlikely for that to be the case because when going to your deployment with no query parameters it has the expected behavior of having the message `Can not find a query parameter: username`. Then, go through each of the booleans (`wantLongTimeAccount`, `wantAncientAccount`, & `wantJoined2020`) and set them individually to true and test to see which ones break your deployment. I am going to go through my code to see what may be causing the error.

**Comment by FlyN-Nick** [comment]
I just went through my code, unfortunately, I could not find anything that should result in an error.

**Comment by FlyN-Nick** [comment]
I just temporarily changed my repo to the changes you made and it worked as expected with no errors, so it turns out it is an issue with your deployment itself.

**Comment by TurnipGuy30** [comment]
OK, I'll try that. Thanks for the help, I'll let you know what happens.

**Comment by TurnipGuy30** [comment]
Huh, I changed it all back to how it was originally, and it still gives an Error 500:

> 500: INTERNAL_SERVER_ERROR
> Code: FUNCTION_INVOCATION_FAILED
> ID: syd1::jhswj-1622896333553-870976b1583c

But thanks anyway! Maybe you could make a fork/branch if the Repo with the code changed...

**Comment by FlyN-Nick** [comment]
Alright, you can use this [link](http://hacked-github-stat-trophies-all-unlocked.vercel.app/) to get all of the secret trophies.

If you want to keep on debugging your Vercel deployment, make sure that the root directory is set to `./`, that the framework preset is set to `Other`, and that you added an environmental variable `GITHUB_TOKEN` with the value of a GitHub PAT that you generated.

**Comment by riverpaper** [comment]
Thanks for the help! I might try Vercel again in the future.
